name: my-docker-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@v5

      - name: check contents
        run: ls -lrth

      - name: Update the commit ID
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA::7}"  >> $GITHUB_ENV
          echo "COMMIT_SHA=${GITHUB_SHA}"  >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF_NAME}"  >> $GITHUB_ENV

      - name: Updates the tags
        run: |
          echo "Full SHA is $COMMIT_SHA"
          echo "LATEST tag is $IMAGE_TAG"
          echo "Branch is $BRANCH"

      - name: build Image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/my-node-app:$IMAGE_TAG .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image
        run: |
          docker push ${{secrets.DOCKER_USERNAME}}/my-node-app:$IMAGE_TAG
          docker tag ${{secrets.DOCKER_USERNAME}}/my-node-app:$IMAGE_TAG ${{secrets.DOCKER_USERNAME}}/my-node-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Push image
        run: |
          docker pull ${{secrets.DOCKER_USERNAME}}/my-node-app:latest
          docker run -d -p 3000:3000 ${{secrets.DOCKER_USERNAME}}/my-node-app:latest
