name: my-docker-app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@v5

      - name: check contents
        run: ls -lrth

      - name: build Image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/my-node-app .

      - name: Push image
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Push image
        run: docker push ${{secrets.DOCKER_USERNAME}}/my-node-app

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Push image
        run: docker pull ${{secrets.DOCKER_USERNAME}}/my-node-app

      - name: Run application
        run: docker run ${{secrets.DOCKER_USERNAME}}/my-node-app
