name: my-docker-app

on:
#  push:
  workflow_dispatch:
    inputs:
      operating_system:
        description: "OS to choose"
        type: choice
        options: ["ubuntu-latest", "windows-latest"]
        required: true
        default: ubuntu-latest
      version:
        description: "version to choose"
        type: choice
        options: ["10", "12", "14"]
        required: true
        default: 10

jobs:
  build:
    # strategy:
    #   matrix:
    #     version: [10, 12, 14]
    #     os: [ubuntu-latest, windows-latest]
    #     exclude:
    #       - os: windows-latest
    runs-on: ${{github.event.inputs.operating_system}}
    steps:
      - name: clone the repo
        uses: actions/checkout@v5

      - name: Update the commit ID
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA::7}"  >> $GITHUB_ENV
          echo "COMMIT_SHA=${GITHUB_SHA}"  >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF_NAME}"  >> $GITHUB_ENV

      - name: Updates the tags
        run: |
          echo "Full SHA is $COMMIT_SHA"
          echo "LATEST tag is $IMAGE_TAG"
          echo "Branch is $BRANCH"

      - name: build Image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/my-node-app:$IMAGE_TAG .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image
        run: |
          docker push ${{secrets.DOCKER_USERNAME}}/my-node-app:$IMAGE_TAG
          docker tag ${{secrets.DOCKER_USERNAME}}/my-node-app:$IMAGE_TAG ${{secrets.DOCKER_USERNAME}}/my-node-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Pull image & run
        run: |
          docker pull ${{secrets.DOCKER_USERNAME}}/my-node-app:latest
          docker run -d -p 3000:3000 ${{secrets.DOCKER_USERNAME}}/my-node-app:latest
